// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pllitcxynrqyurotvupv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbGl0Y3h5bnJxeXVyb3R2dXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTY0MjIsImV4cCI6MjA2MzMzMjQyMn0.b9iASBS2mIEHYKV5-xO1Gsuf_6V4FuF_Hvrh7mW9Fps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);